### ISSUE TITLE
大佬你好，如何实现https透明代理？

### ISSUE THREAD

**Issue by ceshi123qz** [y805939188/easy-proxy#1]
比如我想访问https://www.baidu.com，现在已经将流量转发到proxy了，如果想将流量正常发送到www.baidu.com，是要在proxy里面做配置吗？还是proxy之后转发到的接口。
我尝试在proxy配置目的ip为www.baidu.com和baidu的ip，但是都不能访问到https://www.baidu.com。
在proxy之后的http服务里重定向到https://www.baidu.com，也没成功。

所以请教一下大佬，这应该如何实现

**Comment by y805939188** [comment]
你要是想做这种类似中间人的操作的话，原理应该也是类似的，都是中间这个 proxy 来拦截 client 端的流量，然后 proxy 再作为一个 client 端自己和 server 端建立链接。这个链接可能是可能是单向或者双向的 https 认证。如果想简单一点做单向的，就在自己的 proxy 那层把对方的证书校验关掉。如果想安全一点的话，就在 proxy 那儿加一个自己 client 端的证书做双向认证。我这里之所以不行是因为我这套 golang 代码里头的 proxy 既没关闭来自百度的 https 的校验，也没给让 proxy 自己作为 https client。

**Comment by y805939188** [comment]
> 比如我想访问[https://www.baidu.com，现在已经将流量转发到proxy了，如果想将流量正常发送到www.baidu.com，是要在proxy里面做配置吗？还是proxy之后转发到的接口。](https://www.baidu.com%EF%BC%8C%E7%8E%B0%E5%9C%A8%E5%B7%B2%E7%BB%8F%E5%B0%86%E6%B5%81%E9%87%8F%E8%BD%AC%E5%8F%91%E5%88%B0proxy%E4%BA%86%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%83%B3%E5%B0%86%E6%B5%81%E9%87%8F%E6%AD%A3%E5%B8%B8%E5%8F%91%E9%80%81%E5%88%B0www.baidu.com%EF%BC%8C%E6%98%AF%E8%A6%81%E5%9C%A8proxy%E9%87%8C%E9%9D%A2%E5%81%9A%E9%85%8D%E7%BD%AE%E5%90%97%EF%BC%9F%E8%BF%98%E6%98%AFproxy%E4%B9%8B%E5%90%8E%E8%BD%AC%E5%8F%91%E5%88%B0%E7%9A%84%E6%8E%A5%E5%8F%A3%E3%80%82) 我尝试在proxy配置目的ip为www.baidu.com和baidu的ip，但是都不能访问到[https://www.baidu.com。](https://www.baidu.com%E3%80%82) 在proxy之后的http服务里重定向到[https://www.baidu.com，也没成功。](https://www.baidu.com%EF%BC%8C%E4%B9%9F%E6%B2%A1%E6%88%90%E5%8A%9F%E3%80%82)
> 
> 所以请教一下大佬，这应该如何实现

你要是想做这种类似中间人的操作的话，原理应该也是类似的，都是中间这个 proxy 来拦截 client 端的流量，然后 proxy 再作为一个 client 端自己和 server 端建立链接。这个链接可能是可能是单向或者双向的 https 认证。如果想简单一点做单向的，就在自己的 proxy 那层把对方的证书校验关掉。如果想安全一点的话，就在 proxy 那儿加一个自己 client 端的证书做双向认证。我这里之所以不行是因为我这套 golang 代码里头的 proxy 既没关闭来自百度的 https 的校验，也没给让 proxy 自己作为 https client。
